# Generated by Django 5.2 on 2025-06-11 11:56

from django.db import migrations

import csv
from pathlib import Path


cv_files_path = {"CV_SamplingFeatureType": "../static/data/odm2cvs/samplingfeaturetype.csv",
                  "CV_SamplingFeatureGeoType": "../static/data/odm2cvs/samplingfeaturegeotype.csv",
                  "CV_ElevationDatum": "../static/data/odm2cvs/elevationdatum.csv",
                  "CV_VariableType": "../static/data/odm2cvs/variabletype.csv",
                  "CV_UnitsType": "../static/data/odm2cvs/unitstype.csv",
                  "CV_VariableName": "../static/data/odm2cvs/variablename.csv",
                  "CV_RelationshipType": "../static/data/odm2cvs/relationshiptype.csv",
                  "CV_Medium": "../static/data/odm2cvs/medium.csv",
                  "CV_OrganizationType": "../static/data/odm2cvs/organizationtype.csv",
                  "CV_Speciation": "../static/data/odm2cvs/speciation.csv",
                  "CV_Status": "../static/data/odm2cvs/status.csv",
                  "CV_TaxonomicClassifierType": "../static/data/odm2cvs/taxonomicclassifiertype.csv",
                  "CV_ActionType": "../static/data/odm2cvs/actiontype.csv",
                  "CV_AggregationStatistic": "../static/data/odm2cvs/aggregationstatistic.csv",
                  "CV_QualityCode": "../static/data/odm2cvs/qualitycode.csv",
                  "CV_CensorCode": "../static/data/odm2cvs/censorcode.csv",
                  "CV_ResultType": "../static/data/odm2cvs/resulttype.csv",
                  "CV_MethodType": "../static/data/odm2cvs/methodtype.csv",
                  "CV_SiteType": "../static/data/odm2cvs/sitetype.csv",
                  "CV_DataQualityType": "../static/data/odm2cvs/dataqualitytype.csv",
                }


def load_cvs(apps, schema_editor):
    for model_name, file_path in cv_files_path.items():
        model = apps.get_model('agrogeoinfoapp', model_name)
        full_file_path = Path(__file__).resolve().parent / file_path
        with open(full_file_path, newline='\n', encoding="utf8") as csvfile:
            cvs = csv.reader(csvfile, delimiter=',')
            next(cvs)
            for cv in cvs:
                term, name, definition, category, sourcevocabularyuri, _, _ = cv
                model(term=term, name=name,
                      definition=definition, category=category,
                      sourcevocabularyuri=sourcevocabularyuri
                    ).save()


class Migration(migrations.Migration):

    dependencies = [
        ("agrogeoinfoapp", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(load_cvs)
    ]

